package com.qaii.domain;

public class Govfund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_ApplyTime
     *
     * @mbg.generated
     */
    private String govfundApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Source
     *
     * @mbg.generated
     */
    private String govfundSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Level
     *
     * @mbg.generated
     */
    private String govfundLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Name
     *
     * @mbg.generated
     */
    private String govfundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_ImplementTime
     *
     * @mbg.generated
     */
    private String govfundImplementtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_ConstructUnit
     *
     * @mbg.generated
     */
    private String govfundConstructunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_ManageDepart
     *
     * @mbg.generated
     */
    private String govfundManagedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_ApplyDepart
     *
     * @mbg.generated
     */
    private String govfundApplydepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Pass
     *
     * @mbg.generated
     */
    private String govfundPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_WrittenTime
     *
     * @mbg.generated
     */
    private String govfundWrittentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_FundLimit
     *
     * @mbg.generated
     */
    private String govfundFundlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Fund
     *
     * @mbg.generated
     */
    private String govfundFund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_FundTime
     *
     * @mbg.generated
     */
    private String govfundFundtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_MiddleResult
     *
     * @mbg.generated
     */
    private String govfundMiddleresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_EndResult
     *
     * @mbg.generated
     */
    private String govfundEndresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_Remark
     *
     * @mbg.generated
     */
    private String govfundRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govfund.govfund_File
     *
     * @mbg.generated
     */
    private String govfundFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.id
     *
     * @return the value of sci_govfund.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.id
     *
     * @param id the value for sci_govfund.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_ApplyTime
     *
     * @return the value of sci_govfund.govfund_ApplyTime
     *
     * @mbg.generated
     */
    public String getGovfundApplytime() {
        return govfundApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_ApplyTime
     *
     * @param govfundApplytime the value for sci_govfund.govfund_ApplyTime
     *
     * @mbg.generated
     */
    public void setGovfundApplytime(String govfundApplytime) {
        this.govfundApplytime = govfundApplytime == null ? null : govfundApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Source
     *
     * @return the value of sci_govfund.govfund_Source
     *
     * @mbg.generated
     */
    public String getGovfundSource() {
        return govfundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Source
     *
     * @param govfundSource the value for sci_govfund.govfund_Source
     *
     * @mbg.generated
     */
    public void setGovfundSource(String govfundSource) {
        this.govfundSource = govfundSource == null ? null : govfundSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Level
     *
     * @return the value of sci_govfund.govfund_Level
     *
     * @mbg.generated
     */
    public String getGovfundLevel() {
        return govfundLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Level
     *
     * @param govfundLevel the value for sci_govfund.govfund_Level
     *
     * @mbg.generated
     */
    public void setGovfundLevel(String govfundLevel) {
        this.govfundLevel = govfundLevel == null ? null : govfundLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Name
     *
     * @return the value of sci_govfund.govfund_Name
     *
     * @mbg.generated
     */
    public String getGovfundName() {
        return govfundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Name
     *
     * @param govfundName the value for sci_govfund.govfund_Name
     *
     * @mbg.generated
     */
    public void setGovfundName(String govfundName) {
        this.govfundName = govfundName == null ? null : govfundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_ImplementTime
     *
     * @return the value of sci_govfund.govfund_ImplementTime
     *
     * @mbg.generated
     */
    public String getGovfundImplementtime() {
        return govfundImplementtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_ImplementTime
     *
     * @param govfundImplementtime the value for sci_govfund.govfund_ImplementTime
     *
     * @mbg.generated
     */
    public void setGovfundImplementtime(String govfundImplementtime) {
        this.govfundImplementtime = govfundImplementtime == null ? null : govfundImplementtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_ConstructUnit
     *
     * @return the value of sci_govfund.govfund_ConstructUnit
     *
     * @mbg.generated
     */
    public String getGovfundConstructunit() {
        return govfundConstructunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_ConstructUnit
     *
     * @param govfundConstructunit the value for sci_govfund.govfund_ConstructUnit
     *
     * @mbg.generated
     */
    public void setGovfundConstructunit(String govfundConstructunit) {
        this.govfundConstructunit = govfundConstructunit == null ? null : govfundConstructunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_ManageDepart
     *
     * @return the value of sci_govfund.govfund_ManageDepart
     *
     * @mbg.generated
     */
    public String getGovfundManagedepart() {
        return govfundManagedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_ManageDepart
     *
     * @param govfundManagedepart the value for sci_govfund.govfund_ManageDepart
     *
     * @mbg.generated
     */
    public void setGovfundManagedepart(String govfundManagedepart) {
        this.govfundManagedepart = govfundManagedepart == null ? null : govfundManagedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_ApplyDepart
     *
     * @return the value of sci_govfund.govfund_ApplyDepart
     *
     * @mbg.generated
     */
    public String getGovfundApplydepart() {
        return govfundApplydepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_ApplyDepart
     *
     * @param govfundApplydepart the value for sci_govfund.govfund_ApplyDepart
     *
     * @mbg.generated
     */
    public void setGovfundApplydepart(String govfundApplydepart) {
        this.govfundApplydepart = govfundApplydepart == null ? null : govfundApplydepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Pass
     *
     * @return the value of sci_govfund.govfund_Pass
     *
     * @mbg.generated
     */
    public String getGovfundPass() {
        return govfundPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Pass
     *
     * @param govfundPass the value for sci_govfund.govfund_Pass
     *
     * @mbg.generated
     */
    public void setGovfundPass(String govfundPass) {
        this.govfundPass = govfundPass == null ? null : govfundPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_WrittenTime
     *
     * @return the value of sci_govfund.govfund_WrittenTime
     *
     * @mbg.generated
     */
    public String getGovfundWrittentime() {
        return govfundWrittentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_WrittenTime
     *
     * @param govfundWrittentime the value for sci_govfund.govfund_WrittenTime
     *
     * @mbg.generated
     */
    public void setGovfundWrittentime(String govfundWrittentime) {
        this.govfundWrittentime = govfundWrittentime == null ? null : govfundWrittentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_FundLimit
     *
     * @return the value of sci_govfund.govfund_FundLimit
     *
     * @mbg.generated
     */
    public String getGovfundFundlimit() {
        return govfundFundlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_FundLimit
     *
     * @param govfundFundlimit the value for sci_govfund.govfund_FundLimit
     *
     * @mbg.generated
     */
    public void setGovfundFundlimit(String govfundFundlimit) {
        this.govfundFundlimit = govfundFundlimit == null ? null : govfundFundlimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Fund
     *
     * @return the value of sci_govfund.govfund_Fund
     *
     * @mbg.generated
     */
    public String getGovfundFund() {
        return govfundFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Fund
     *
     * @param govfundFund the value for sci_govfund.govfund_Fund
     *
     * @mbg.generated
     */
    public void setGovfundFund(String govfundFund) {
        this.govfundFund = govfundFund == null ? null : govfundFund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_FundTime
     *
     * @return the value of sci_govfund.govfund_FundTime
     *
     * @mbg.generated
     */
    public String getGovfundFundtime() {
        return govfundFundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_FundTime
     *
     * @param govfundFundtime the value for sci_govfund.govfund_FundTime
     *
     * @mbg.generated
     */
    public void setGovfundFundtime(String govfundFundtime) {
        this.govfundFundtime = govfundFundtime == null ? null : govfundFundtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_MiddleResult
     *
     * @return the value of sci_govfund.govfund_MiddleResult
     *
     * @mbg.generated
     */
    public String getGovfundMiddleresult() {
        return govfundMiddleresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_MiddleResult
     *
     * @param govfundMiddleresult the value for sci_govfund.govfund_MiddleResult
     *
     * @mbg.generated
     */
    public void setGovfundMiddleresult(String govfundMiddleresult) {
        this.govfundMiddleresult = govfundMiddleresult == null ? null : govfundMiddleresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_EndResult
     *
     * @return the value of sci_govfund.govfund_EndResult
     *
     * @mbg.generated
     */
    public String getGovfundEndresult() {
        return govfundEndresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_EndResult
     *
     * @param govfundEndresult the value for sci_govfund.govfund_EndResult
     *
     * @mbg.generated
     */
    public void setGovfundEndresult(String govfundEndresult) {
        this.govfundEndresult = govfundEndresult == null ? null : govfundEndresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_Remark
     *
     * @return the value of sci_govfund.govfund_Remark
     *
     * @mbg.generated
     */
    public String getGovfundRemark() {
        return govfundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_Remark
     *
     * @param govfundRemark the value for sci_govfund.govfund_Remark
     *
     * @mbg.generated
     */
    public void setGovfundRemark(String govfundRemark) {
        this.govfundRemark = govfundRemark == null ? null : govfundRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govfund.govfund_File
     *
     * @return the value of sci_govfund.govfund_File
     *
     * @mbg.generated
     */
    public String getGovfundFile() {
        return govfundFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govfund.govfund_File
     *
     * @param govfundFile the value for sci_govfund.govfund_File
     *
     * @mbg.generated
     */
    public void setGovfundFile(String govfundFile) {
        this.govfundFile = govfundFile == null ? null : govfundFile.trim();
    }
}