package com.qaii.domain;

public class Govplatform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ApplyTime
     *
     * @mbg.generated
     */
    private String govplatApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_Source
     *
     * @mbg.generated
     */
    private String govplatSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_Level
     *
     * @mbg.generated
     */
    private String govplatLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_Name
     *
     * @mbg.generated
     */
    private String govplatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ImplementTime
     *
     * @mbg.generated
     */
    private String govplatImplementtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_DutyUnit
     *
     * @mbg.generated
     */
    private String govplatDutyunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_CooperationUnit
     *
     * @mbg.generated
     */
    private String govplatCooperationunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ManageDepart
     *
     * @mbg.generated
     */
    private String govplatManagedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ApplyDepart
     *
     * @mbg.generated
     */
    private String govplatApplydepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_AssumeDepart
     *
     * @mbg.generated
     */
    private String govplatAssumedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_PlatformPer
     *
     * @mbg.generated
     */
    private String govplatPlatformper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ProjectApproval
     *
     * @mbg.generated
     */
    private String govplatProjectapproval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_ApprovalNum
     *
     * @mbg.generated
     */
    private String govplatApprovalnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_Subvention
     *
     * @mbg.generated
     */
    private String govplatSubvention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_FundTime
     *
     * @mbg.generated
     */
    private String govplatFundtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_MiddleResult
     *
     * @mbg.generated
     */
    private String govplatMiddleresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_YearResult
     *
     * @mbg.generated
     */
    private String govplatYearresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_EndResult
     *
     * @mbg.generated
     */
    private String govplatEndresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_Remark
     *
     * @mbg.generated
     */
    private String govplatRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govplatform.govplat_File
     *
     * @mbg.generated
     */
    private String govplatFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.id
     *
     * @return the value of sci_govplatform.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.id
     *
     * @param id the value for sci_govplatform.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ApplyTime
     *
     * @return the value of sci_govplatform.govplat_ApplyTime
     *
     * @mbg.generated
     */
    public String getGovplatApplytime() {
        return govplatApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ApplyTime
     *
     * @param govplatApplytime the value for sci_govplatform.govplat_ApplyTime
     *
     * @mbg.generated
     */
    public void setGovplatApplytime(String govplatApplytime) {
        this.govplatApplytime = govplatApplytime == null ? null : govplatApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_Source
     *
     * @return the value of sci_govplatform.govplat_Source
     *
     * @mbg.generated
     */
    public String getGovplatSource() {
        return govplatSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_Source
     *
     * @param govplatSource the value for sci_govplatform.govplat_Source
     *
     * @mbg.generated
     */
    public void setGovplatSource(String govplatSource) {
        this.govplatSource = govplatSource == null ? null : govplatSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_Level
     *
     * @return the value of sci_govplatform.govplat_Level
     *
     * @mbg.generated
     */
    public String getGovplatLevel() {
        return govplatLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_Level
     *
     * @param govplatLevel the value for sci_govplatform.govplat_Level
     *
     * @mbg.generated
     */
    public void setGovplatLevel(String govplatLevel) {
        this.govplatLevel = govplatLevel == null ? null : govplatLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_Name
     *
     * @return the value of sci_govplatform.govplat_Name
     *
     * @mbg.generated
     */
    public String getGovplatName() {
        return govplatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_Name
     *
     * @param govplatName the value for sci_govplatform.govplat_Name
     *
     * @mbg.generated
     */
    public void setGovplatName(String govplatName) {
        this.govplatName = govplatName == null ? null : govplatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ImplementTime
     *
     * @return the value of sci_govplatform.govplat_ImplementTime
     *
     * @mbg.generated
     */
    public String getGovplatImplementtime() {
        return govplatImplementtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ImplementTime
     *
     * @param govplatImplementtime the value for sci_govplatform.govplat_ImplementTime
     *
     * @mbg.generated
     */
    public void setGovplatImplementtime(String govplatImplementtime) {
        this.govplatImplementtime = govplatImplementtime == null ? null : govplatImplementtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_DutyUnit
     *
     * @return the value of sci_govplatform.govplat_DutyUnit
     *
     * @mbg.generated
     */
    public String getGovplatDutyunit() {
        return govplatDutyunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_DutyUnit
     *
     * @param govplatDutyunit the value for sci_govplatform.govplat_DutyUnit
     *
     * @mbg.generated
     */
    public void setGovplatDutyunit(String govplatDutyunit) {
        this.govplatDutyunit = govplatDutyunit == null ? null : govplatDutyunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_CooperationUnit
     *
     * @return the value of sci_govplatform.govplat_CooperationUnit
     *
     * @mbg.generated
     */
    public String getGovplatCooperationunit() {
        return govplatCooperationunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_CooperationUnit
     *
     * @param govplatCooperationunit the value for sci_govplatform.govplat_CooperationUnit
     *
     * @mbg.generated
     */
    public void setGovplatCooperationunit(String govplatCooperationunit) {
        this.govplatCooperationunit = govplatCooperationunit == null ? null : govplatCooperationunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ManageDepart
     *
     * @return the value of sci_govplatform.govplat_ManageDepart
     *
     * @mbg.generated
     */
    public String getGovplatManagedepart() {
        return govplatManagedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ManageDepart
     *
     * @param govplatManagedepart the value for sci_govplatform.govplat_ManageDepart
     *
     * @mbg.generated
     */
    public void setGovplatManagedepart(String govplatManagedepart) {
        this.govplatManagedepart = govplatManagedepart == null ? null : govplatManagedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ApplyDepart
     *
     * @return the value of sci_govplatform.govplat_ApplyDepart
     *
     * @mbg.generated
     */
    public String getGovplatApplydepart() {
        return govplatApplydepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ApplyDepart
     *
     * @param govplatApplydepart the value for sci_govplatform.govplat_ApplyDepart
     *
     * @mbg.generated
     */
    public void setGovplatApplydepart(String govplatApplydepart) {
        this.govplatApplydepart = govplatApplydepart == null ? null : govplatApplydepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_AssumeDepart
     *
     * @return the value of sci_govplatform.govplat_AssumeDepart
     *
     * @mbg.generated
     */
    public String getGovplatAssumedepart() {
        return govplatAssumedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_AssumeDepart
     *
     * @param govplatAssumedepart the value for sci_govplatform.govplat_AssumeDepart
     *
     * @mbg.generated
     */
    public void setGovplatAssumedepart(String govplatAssumedepart) {
        this.govplatAssumedepart = govplatAssumedepart == null ? null : govplatAssumedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_PlatformPer
     *
     * @return the value of sci_govplatform.govplat_PlatformPer
     *
     * @mbg.generated
     */
    public String getGovplatPlatformper() {
        return govplatPlatformper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_PlatformPer
     *
     * @param govplatPlatformper the value for sci_govplatform.govplat_PlatformPer
     *
     * @mbg.generated
     */
    public void setGovplatPlatformper(String govplatPlatformper) {
        this.govplatPlatformper = govplatPlatformper == null ? null : govplatPlatformper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ProjectApproval
     *
     * @return the value of sci_govplatform.govplat_ProjectApproval
     *
     * @mbg.generated
     */
    public String getGovplatProjectapproval() {
        return govplatProjectapproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ProjectApproval
     *
     * @param govplatProjectapproval the value for sci_govplatform.govplat_ProjectApproval
     *
     * @mbg.generated
     */
    public void setGovplatProjectapproval(String govplatProjectapproval) {
        this.govplatProjectapproval = govplatProjectapproval == null ? null : govplatProjectapproval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_ApprovalNum
     *
     * @return the value of sci_govplatform.govplat_ApprovalNum
     *
     * @mbg.generated
     */
    public String getGovplatApprovalnum() {
        return govplatApprovalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_ApprovalNum
     *
     * @param govplatApprovalnum the value for sci_govplatform.govplat_ApprovalNum
     *
     * @mbg.generated
     */
    public void setGovplatApprovalnum(String govplatApprovalnum) {
        this.govplatApprovalnum = govplatApprovalnum == null ? null : govplatApprovalnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_Subvention
     *
     * @return the value of sci_govplatform.govplat_Subvention
     *
     * @mbg.generated
     */
    public String getGovplatSubvention() {
        return govplatSubvention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_Subvention
     *
     * @param govplatSubvention the value for sci_govplatform.govplat_Subvention
     *
     * @mbg.generated
     */
    public void setGovplatSubvention(String govplatSubvention) {
        this.govplatSubvention = govplatSubvention == null ? null : govplatSubvention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_FundTime
     *
     * @return the value of sci_govplatform.govplat_FundTime
     *
     * @mbg.generated
     */
    public String getGovplatFundtime() {
        return govplatFundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_FundTime
     *
     * @param govplatFundtime the value for sci_govplatform.govplat_FundTime
     *
     * @mbg.generated
     */
    public void setGovplatFundtime(String govplatFundtime) {
        this.govplatFundtime = govplatFundtime == null ? null : govplatFundtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_MiddleResult
     *
     * @return the value of sci_govplatform.govplat_MiddleResult
     *
     * @mbg.generated
     */
    public String getGovplatMiddleresult() {
        return govplatMiddleresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_MiddleResult
     *
     * @param govplatMiddleresult the value for sci_govplatform.govplat_MiddleResult
     *
     * @mbg.generated
     */
    public void setGovplatMiddleresult(String govplatMiddleresult) {
        this.govplatMiddleresult = govplatMiddleresult == null ? null : govplatMiddleresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_YearResult
     *
     * @return the value of sci_govplatform.govplat_YearResult
     *
     * @mbg.generated
     */
    public String getGovplatYearresult() {
        return govplatYearresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_YearResult
     *
     * @param govplatYearresult the value for sci_govplatform.govplat_YearResult
     *
     * @mbg.generated
     */
    public void setGovplatYearresult(String govplatYearresult) {
        this.govplatYearresult = govplatYearresult == null ? null : govplatYearresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_EndResult
     *
     * @return the value of sci_govplatform.govplat_EndResult
     *
     * @mbg.generated
     */
    public String getGovplatEndresult() {
        return govplatEndresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_EndResult
     *
     * @param govplatEndresult the value for sci_govplatform.govplat_EndResult
     *
     * @mbg.generated
     */
    public void setGovplatEndresult(String govplatEndresult) {
        this.govplatEndresult = govplatEndresult == null ? null : govplatEndresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_Remark
     *
     * @return the value of sci_govplatform.govplat_Remark
     *
     * @mbg.generated
     */
    public String getGovplatRemark() {
        return govplatRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_Remark
     *
     * @param govplatRemark the value for sci_govplatform.govplat_Remark
     *
     * @mbg.generated
     */
    public void setGovplatRemark(String govplatRemark) {
        this.govplatRemark = govplatRemark == null ? null : govplatRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govplatform.govplat_File
     *
     * @return the value of sci_govplatform.govplat_File
     *
     * @mbg.generated
     */
    public String getGovplatFile() {
        return govplatFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govplatform.govplat_File
     *
     * @param govplatFile the value for sci_govplatform.govplat_File
     *
     * @mbg.generated
     */
    public void setGovplatFile(String govplatFile) {
        this.govplatFile = govplatFile == null ? null : govplatFile.trim();
    }
}