package com.qaii.domain;

public class Govreward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_ApplyTime
     *
     * @mbg.generated
     */
    private String rewardApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_Source
     *
     * @mbg.generated
     */
    private String rewardSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_Level
     *
     * @mbg.generated
     */
    private String rewardLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_Name
     *
     * @mbg.generated
     */
    private String rewardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_ProjectName
     *
     * @mbg.generated
     */
    private String rewardProjectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_DutyUnit
     *
     * @mbg.generated
     */
    private String rewardDutyunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_CooperationUnit
     *
     * @mbg.generated
     */
    private String rewardCooperationunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_ManageDepart
     *
     * @mbg.generated
     */
    private String rewardManagedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_ApplyDepart
     *
     * @mbg.generated
     */
    private String rewardApplydepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_AssumeDepart
     *
     * @mbg.generated
     */
    private String rewardAssumedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_Award
     *
     * @mbg.generated
     */
    private String rewardAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_AwardTime
     *
     * @mbg.generated
     */
    private String rewardAwardtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_AwardNum
     *
     * @mbg.generated
     */
    private String rewardAwardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govreward.reward_FundTime
     *
     * @mbg.generated
     */
    private String rewardFundtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.id
     *
     * @return the value of sci_govreward.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.id
     *
     * @param id the value for sci_govreward.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_ApplyTime
     *
     * @return the value of sci_govreward.reward_ApplyTime
     *
     * @mbg.generated
     */
    public String getRewardApplytime() {
        return rewardApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_ApplyTime
     *
     * @param rewardApplytime the value for sci_govreward.reward_ApplyTime
     *
     * @mbg.generated
     */
    public void setRewardApplytime(String rewardApplytime) {
        this.rewardApplytime = rewardApplytime == null ? null : rewardApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_Source
     *
     * @return the value of sci_govreward.reward_Source
     *
     * @mbg.generated
     */
    public String getRewardSource() {
        return rewardSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_Source
     *
     * @param rewardSource the value for sci_govreward.reward_Source
     *
     * @mbg.generated
     */
    public void setRewardSource(String rewardSource) {
        this.rewardSource = rewardSource == null ? null : rewardSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_Level
     *
     * @return the value of sci_govreward.reward_Level
     *
     * @mbg.generated
     */
    public String getRewardLevel() {
        return rewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_Level
     *
     * @param rewardLevel the value for sci_govreward.reward_Level
     *
     * @mbg.generated
     */
    public void setRewardLevel(String rewardLevel) {
        this.rewardLevel = rewardLevel == null ? null : rewardLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_Name
     *
     * @return the value of sci_govreward.reward_Name
     *
     * @mbg.generated
     */
    public String getRewardName() {
        return rewardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_Name
     *
     * @param rewardName the value for sci_govreward.reward_Name
     *
     * @mbg.generated
     */
    public void setRewardName(String rewardName) {
        this.rewardName = rewardName == null ? null : rewardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_ProjectName
     *
     * @return the value of sci_govreward.reward_ProjectName
     *
     * @mbg.generated
     */
    public String getRewardProjectname() {
        return rewardProjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_ProjectName
     *
     * @param rewardProjectname the value for sci_govreward.reward_ProjectName
     *
     * @mbg.generated
     */
    public void setRewardProjectname(String rewardProjectname) {
        this.rewardProjectname = rewardProjectname == null ? null : rewardProjectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_DutyUnit
     *
     * @return the value of sci_govreward.reward_DutyUnit
     *
     * @mbg.generated
     */
    public String getRewardDutyunit() {
        return rewardDutyunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_DutyUnit
     *
     * @param rewardDutyunit the value for sci_govreward.reward_DutyUnit
     *
     * @mbg.generated
     */
    public void setRewardDutyunit(String rewardDutyunit) {
        this.rewardDutyunit = rewardDutyunit == null ? null : rewardDutyunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_CooperationUnit
     *
     * @return the value of sci_govreward.reward_CooperationUnit
     *
     * @mbg.generated
     */
    public String getRewardCooperationunit() {
        return rewardCooperationunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_CooperationUnit
     *
     * @param rewardCooperationunit the value for sci_govreward.reward_CooperationUnit
     *
     * @mbg.generated
     */
    public void setRewardCooperationunit(String rewardCooperationunit) {
        this.rewardCooperationunit = rewardCooperationunit == null ? null : rewardCooperationunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_ManageDepart
     *
     * @return the value of sci_govreward.reward_ManageDepart
     *
     * @mbg.generated
     */
    public String getRewardManagedepart() {
        return rewardManagedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_ManageDepart
     *
     * @param rewardManagedepart the value for sci_govreward.reward_ManageDepart
     *
     * @mbg.generated
     */
    public void setRewardManagedepart(String rewardManagedepart) {
        this.rewardManagedepart = rewardManagedepart == null ? null : rewardManagedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_ApplyDepart
     *
     * @return the value of sci_govreward.reward_ApplyDepart
     *
     * @mbg.generated
     */
    public String getRewardApplydepart() {
        return rewardApplydepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_ApplyDepart
     *
     * @param rewardApplydepart the value for sci_govreward.reward_ApplyDepart
     *
     * @mbg.generated
     */
    public void setRewardApplydepart(String rewardApplydepart) {
        this.rewardApplydepart = rewardApplydepart == null ? null : rewardApplydepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_AssumeDepart
     *
     * @return the value of sci_govreward.reward_AssumeDepart
     *
     * @mbg.generated
     */
    public String getRewardAssumedepart() {
        return rewardAssumedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_AssumeDepart
     *
     * @param rewardAssumedepart the value for sci_govreward.reward_AssumeDepart
     *
     * @mbg.generated
     */
    public void setRewardAssumedepart(String rewardAssumedepart) {
        this.rewardAssumedepart = rewardAssumedepart == null ? null : rewardAssumedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_Award
     *
     * @return the value of sci_govreward.reward_Award
     *
     * @mbg.generated
     */
    public String getRewardAward() {
        return rewardAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_Award
     *
     * @param rewardAward the value for sci_govreward.reward_Award
     *
     * @mbg.generated
     */
    public void setRewardAward(String rewardAward) {
        this.rewardAward = rewardAward == null ? null : rewardAward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_AwardTime
     *
     * @return the value of sci_govreward.reward_AwardTime
     *
     * @mbg.generated
     */
    public String getRewardAwardtime() {
        return rewardAwardtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_AwardTime
     *
     * @param rewardAwardtime the value for sci_govreward.reward_AwardTime
     *
     * @mbg.generated
     */
    public void setRewardAwardtime(String rewardAwardtime) {
        this.rewardAwardtime = rewardAwardtime == null ? null : rewardAwardtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_AwardNum
     *
     * @return the value of sci_govreward.reward_AwardNum
     *
     * @mbg.generated
     */
    public String getRewardAwardnum() {
        return rewardAwardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_AwardNum
     *
     * @param rewardAwardnum the value for sci_govreward.reward_AwardNum
     *
     * @mbg.generated
     */
    public void setRewardAwardnum(String rewardAwardnum) {
        this.rewardAwardnum = rewardAwardnum == null ? null : rewardAwardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govreward.reward_FundTime
     *
     * @return the value of sci_govreward.reward_FundTime
     *
     * @mbg.generated
     */
    public String getRewardFundtime() {
        return rewardFundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govreward.reward_FundTime
     *
     * @param rewardFundtime the value for sci_govreward.reward_FundTime
     *
     * @mbg.generated
     */
    public void setRewardFundtime(String rewardFundtime) {
        this.rewardFundtime = rewardFundtime == null ? null : rewardFundtime.trim();
    }
}