package com.qaii.domain;

public class Govsubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ApplyTime
     *
     * @mbg.generated
     */
    private String govsubApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_Source
     *
     * @mbg.generated
     */
    private String govsubSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_Level
     *
     * @mbg.generated
     */
    private String govsubLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_Name
     *
     * @mbg.generated
     */
    private String govsubName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ImplementTime
     *
     * @mbg.generated
     */
    private String govsubImplementtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_DutyUnit
     *
     * @mbg.generated
     */
    private String govsubDutyunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_CooperationUnit
     *
     * @mbg.generated
     */
    private String govsubCooperationunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ManageDepart
     *
     * @mbg.generated
     */
    private String govsubManagedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ApplyDepart
     *
     * @mbg.generated
     */
    private String govsubApplydepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_AssumeDepart
     *
     * @mbg.generated
     */
    private String govsubAssumedepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ProjectPer
     *
     * @mbg.generated
     */
    private String govsubProjectper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ProjectApproval
     *
     * @mbg.generated
     */
    private String govsubProjectapproval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_ApprovalNum
     *
     * @mbg.generated
     */
    private String govsubApprovalnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_Subvention
     *
     * @mbg.generated
     */
    private String govsubSubvention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_FundTime
     *
     * @mbg.generated
     */
    private String govsubFundtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_MiddleResult
     *
     * @mbg.generated
     */
    private String govsubMiddleresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_YearResult
     *
     * @mbg.generated
     */
    private String govsubYearresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_EndResult
     *
     * @mbg.generated
     */
    private String govsubEndresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_Remark
     *
     * @mbg.generated
     */
    private String govsubRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_govsubject.govsub_File
     *
     * @mbg.generated
     */
    private String govsubFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.id
     *
     * @return the value of sci_govsubject.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.id
     *
     * @param id the value for sci_govsubject.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ApplyTime
     *
     * @return the value of sci_govsubject.govsub_ApplyTime
     *
     * @mbg.generated
     */
    public String getGovsubApplytime() {
        return govsubApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ApplyTime
     *
     * @param govsubApplytime the value for sci_govsubject.govsub_ApplyTime
     *
     * @mbg.generated
     */
    public void setGovsubApplytime(String govsubApplytime) {
        this.govsubApplytime = govsubApplytime == null ? null : govsubApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_Source
     *
     * @return the value of sci_govsubject.govsub_Source
     *
     * @mbg.generated
     */
    public String getGovsubSource() {
        return govsubSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_Source
     *
     * @param govsubSource the value for sci_govsubject.govsub_Source
     *
     * @mbg.generated
     */
    public void setGovsubSource(String govsubSource) {
        this.govsubSource = govsubSource == null ? null : govsubSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_Level
     *
     * @return the value of sci_govsubject.govsub_Level
     *
     * @mbg.generated
     */
    public String getGovsubLevel() {
        return govsubLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_Level
     *
     * @param govsubLevel the value for sci_govsubject.govsub_Level
     *
     * @mbg.generated
     */
    public void setGovsubLevel(String govsubLevel) {
        this.govsubLevel = govsubLevel == null ? null : govsubLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_Name
     *
     * @return the value of sci_govsubject.govsub_Name
     *
     * @mbg.generated
     */
    public String getGovsubName() {
        return govsubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_Name
     *
     * @param govsubName the value for sci_govsubject.govsub_Name
     *
     * @mbg.generated
     */
    public void setGovsubName(String govsubName) {
        this.govsubName = govsubName == null ? null : govsubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ImplementTime
     *
     * @return the value of sci_govsubject.govsub_ImplementTime
     *
     * @mbg.generated
     */
    public String getGovsubImplementtime() {
        return govsubImplementtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ImplementTime
     *
     * @param govsubImplementtime the value for sci_govsubject.govsub_ImplementTime
     *
     * @mbg.generated
     */
    public void setGovsubImplementtime(String govsubImplementtime) {
        this.govsubImplementtime = govsubImplementtime == null ? null : govsubImplementtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_DutyUnit
     *
     * @return the value of sci_govsubject.govsub_DutyUnit
     *
     * @mbg.generated
     */
    public String getGovsubDutyunit() {
        return govsubDutyunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_DutyUnit
     *
     * @param govsubDutyunit the value for sci_govsubject.govsub_DutyUnit
     *
     * @mbg.generated
     */
    public void setGovsubDutyunit(String govsubDutyunit) {
        this.govsubDutyunit = govsubDutyunit == null ? null : govsubDutyunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_CooperationUnit
     *
     * @return the value of sci_govsubject.govsub_CooperationUnit
     *
     * @mbg.generated
     */
    public String getGovsubCooperationunit() {
        return govsubCooperationunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_CooperationUnit
     *
     * @param govsubCooperationunit the value for sci_govsubject.govsub_CooperationUnit
     *
     * @mbg.generated
     */
    public void setGovsubCooperationunit(String govsubCooperationunit) {
        this.govsubCooperationunit = govsubCooperationunit == null ? null : govsubCooperationunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ManageDepart
     *
     * @return the value of sci_govsubject.govsub_ManageDepart
     *
     * @mbg.generated
     */
    public String getGovsubManagedepart() {
        return govsubManagedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ManageDepart
     *
     * @param govsubManagedepart the value for sci_govsubject.govsub_ManageDepart
     *
     * @mbg.generated
     */
    public void setGovsubManagedepart(String govsubManagedepart) {
        this.govsubManagedepart = govsubManagedepart == null ? null : govsubManagedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ApplyDepart
     *
     * @return the value of sci_govsubject.govsub_ApplyDepart
     *
     * @mbg.generated
     */
    public String getGovsubApplydepart() {
        return govsubApplydepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ApplyDepart
     *
     * @param govsubApplydepart the value for sci_govsubject.govsub_ApplyDepart
     *
     * @mbg.generated
     */
    public void setGovsubApplydepart(String govsubApplydepart) {
        this.govsubApplydepart = govsubApplydepart == null ? null : govsubApplydepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_AssumeDepart
     *
     * @return the value of sci_govsubject.govsub_AssumeDepart
     *
     * @mbg.generated
     */
    public String getGovsubAssumedepart() {
        return govsubAssumedepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_AssumeDepart
     *
     * @param govsubAssumedepart the value for sci_govsubject.govsub_AssumeDepart
     *
     * @mbg.generated
     */
    public void setGovsubAssumedepart(String govsubAssumedepart) {
        this.govsubAssumedepart = govsubAssumedepart == null ? null : govsubAssumedepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ProjectPer
     *
     * @return the value of sci_govsubject.govsub_ProjectPer
     *
     * @mbg.generated
     */
    public String getGovsubProjectper() {
        return govsubProjectper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ProjectPer
     *
     * @param govsubProjectper the value for sci_govsubject.govsub_ProjectPer
     *
     * @mbg.generated
     */
    public void setGovsubProjectper(String govsubProjectper) {
        this.govsubProjectper = govsubProjectper == null ? null : govsubProjectper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ProjectApproval
     *
     * @return the value of sci_govsubject.govsub_ProjectApproval
     *
     * @mbg.generated
     */
    public String getGovsubProjectapproval() {
        return govsubProjectapproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ProjectApproval
     *
     * @param govsubProjectapproval the value for sci_govsubject.govsub_ProjectApproval
     *
     * @mbg.generated
     */
    public void setGovsubProjectapproval(String govsubProjectapproval) {
        this.govsubProjectapproval = govsubProjectapproval == null ? null : govsubProjectapproval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_ApprovalNum
     *
     * @return the value of sci_govsubject.govsub_ApprovalNum
     *
     * @mbg.generated
     */
    public String getGovsubApprovalnum() {
        return govsubApprovalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_ApprovalNum
     *
     * @param govsubApprovalnum the value for sci_govsubject.govsub_ApprovalNum
     *
     * @mbg.generated
     */
    public void setGovsubApprovalnum(String govsubApprovalnum) {
        this.govsubApprovalnum = govsubApprovalnum == null ? null : govsubApprovalnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_Subvention
     *
     * @return the value of sci_govsubject.govsub_Subvention
     *
     * @mbg.generated
     */
    public String getGovsubSubvention() {
        return govsubSubvention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_Subvention
     *
     * @param govsubSubvention the value for sci_govsubject.govsub_Subvention
     *
     * @mbg.generated
     */
    public void setGovsubSubvention(String govsubSubvention) {
        this.govsubSubvention = govsubSubvention == null ? null : govsubSubvention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_FundTime
     *
     * @return the value of sci_govsubject.govsub_FundTime
     *
     * @mbg.generated
     */
    public String getGovsubFundtime() {
        return govsubFundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_FundTime
     *
     * @param govsubFundtime the value for sci_govsubject.govsub_FundTime
     *
     * @mbg.generated
     */
    public void setGovsubFundtime(String govsubFundtime) {
        this.govsubFundtime = govsubFundtime == null ? null : govsubFundtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_MiddleResult
     *
     * @return the value of sci_govsubject.govsub_MiddleResult
     *
     * @mbg.generated
     */
    public String getGovsubMiddleresult() {
        return govsubMiddleresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_MiddleResult
     *
     * @param govsubMiddleresult the value for sci_govsubject.govsub_MiddleResult
     *
     * @mbg.generated
     */
    public void setGovsubMiddleresult(String govsubMiddleresult) {
        this.govsubMiddleresult = govsubMiddleresult == null ? null : govsubMiddleresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_YearResult
     *
     * @return the value of sci_govsubject.govsub_YearResult
     *
     * @mbg.generated
     */
    public String getGovsubYearresult() {
        return govsubYearresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_YearResult
     *
     * @param govsubYearresult the value for sci_govsubject.govsub_YearResult
     *
     * @mbg.generated
     */
    public void setGovsubYearresult(String govsubYearresult) {
        this.govsubYearresult = govsubYearresult == null ? null : govsubYearresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_EndResult
     *
     * @return the value of sci_govsubject.govsub_EndResult
     *
     * @mbg.generated
     */
    public String getGovsubEndresult() {
        return govsubEndresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_EndResult
     *
     * @param govsubEndresult the value for sci_govsubject.govsub_EndResult
     *
     * @mbg.generated
     */
    public void setGovsubEndresult(String govsubEndresult) {
        this.govsubEndresult = govsubEndresult == null ? null : govsubEndresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_Remark
     *
     * @return the value of sci_govsubject.govsub_Remark
     *
     * @mbg.generated
     */
    public String getGovsubRemark() {
        return govsubRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_Remark
     *
     * @param govsubRemark the value for sci_govsubject.govsub_Remark
     *
     * @mbg.generated
     */
    public void setGovsubRemark(String govsubRemark) {
        this.govsubRemark = govsubRemark == null ? null : govsubRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_govsubject.govsub_File
     *
     * @return the value of sci_govsubject.govsub_File
     *
     * @mbg.generated
     */
    public String getGovsubFile() {
        return govsubFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_govsubject.govsub_File
     *
     * @param govsubFile the value for sci_govsubject.govsub_File
     *
     * @mbg.generated
     */
    public void setGovsubFile(String govsubFile) {
        this.govsubFile = govsubFile == null ? null : govsubFile.trim();
    }
}