package com.qaii.domain;

public class Patent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Dept
     *
     * @mbg.generated
     */
    private String patDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Code
     *
     * @mbg.generated
     */
    private String patCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Type
     *
     * @mbg.generated
     */
    private String patType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Name
     *
     * @mbg.generated
     */
    private String patName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Digest
     *
     * @mbg.generated
     */
    private String patDigest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Author
     *
     * @mbg.generated
     */
    private String patAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_ApplyPer
     *
     * @mbg.generated
     */
    private String patApplyper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_TellTime
     *
     * @mbg.generated
     */
    private String patTelltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Agency
     *
     * @mbg.generated
     */
    private String patAgency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_PrePublishAudit
     *
     * @mbg.generated
     */
    private String patPrepublishaudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_ApplyNum
     *
     * @mbg.generated
     */
    private String patApplynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_ApplyTime
     *
     * @mbg.generated
     */
    private String patApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_PublishNum
     *
     * @mbg.generated
     */
    private String patPublishnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_PublishTime
     *
     * @mbg.generated
     */
    private String patPublishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_AuthorzationTime
     *
     * @mbg.generated
     */
    private String patAuthorzationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Remission
     *
     * @mbg.generated
     */
    private String patRemission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Cost
     *
     * @mbg.generated
     */
    private String patCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_InvoicePer
     *
     * @mbg.generated
     */
    private String patInvoiceper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Remark
     *
     * @mbg.generated
     */
    private String patRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Penner
     *
     * @mbg.generated
     */
    private String patPenner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_patent.pat_Agent
     *
     * @mbg.generated
     */
    private String patAgent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.id
     *
     * @return the value of sci_patent.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.id
     *
     * @param id the value for sci_patent.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Dept
     *
     * @return the value of sci_patent.pat_Dept
     *
     * @mbg.generated
     */
    public String getPatDept() {
        return patDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Dept
     *
     * @param patDept the value for sci_patent.pat_Dept
     *
     * @mbg.generated
     */
    public void setPatDept(String patDept) {
        this.patDept = patDept == null ? null : patDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Code
     *
     * @return the value of sci_patent.pat_Code
     *
     * @mbg.generated
     */
    public String getPatCode() {
        return patCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Code
     *
     * @param patCode the value for sci_patent.pat_Code
     *
     * @mbg.generated
     */
    public void setPatCode(String patCode) {
        this.patCode = patCode == null ? null : patCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Type
     *
     * @return the value of sci_patent.pat_Type
     *
     * @mbg.generated
     */
    public String getPatType() {
        return patType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Type
     *
     * @param patType the value for sci_patent.pat_Type
     *
     * @mbg.generated
     */
    public void setPatType(String patType) {
        this.patType = patType == null ? null : patType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Name
     *
     * @return the value of sci_patent.pat_Name
     *
     * @mbg.generated
     */
    public String getPatName() {
        return patName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Name
     *
     * @param patName the value for sci_patent.pat_Name
     *
     * @mbg.generated
     */
    public void setPatName(String patName) {
        this.patName = patName == null ? null : patName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Digest
     *
     * @return the value of sci_patent.pat_Digest
     *
     * @mbg.generated
     */
    public String getPatDigest() {
        return patDigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Digest
     *
     * @param patDigest the value for sci_patent.pat_Digest
     *
     * @mbg.generated
     */
    public void setPatDigest(String patDigest) {
        this.patDigest = patDigest == null ? null : patDigest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Author
     *
     * @return the value of sci_patent.pat_Author
     *
     * @mbg.generated
     */
    public String getPatAuthor() {
        return patAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Author
     *
     * @param patAuthor the value for sci_patent.pat_Author
     *
     * @mbg.generated
     */
    public void setPatAuthor(String patAuthor) {
        this.patAuthor = patAuthor == null ? null : patAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_ApplyPer
     *
     * @return the value of sci_patent.pat_ApplyPer
     *
     * @mbg.generated
     */
    public String getPatApplyper() {
        return patApplyper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_ApplyPer
     *
     * @param patApplyper the value for sci_patent.pat_ApplyPer
     *
     * @mbg.generated
     */
    public void setPatApplyper(String patApplyper) {
        this.patApplyper = patApplyper == null ? null : patApplyper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_TellTime
     *
     * @return the value of sci_patent.pat_TellTime
     *
     * @mbg.generated
     */
    public String getPatTelltime() {
        return patTelltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_TellTime
     *
     * @param patTelltime the value for sci_patent.pat_TellTime
     *
     * @mbg.generated
     */
    public void setPatTelltime(String patTelltime) {
        this.patTelltime = patTelltime == null ? null : patTelltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Agency
     *
     * @return the value of sci_patent.pat_Agency
     *
     * @mbg.generated
     */
    public String getPatAgency() {
        return patAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Agency
     *
     * @param patAgency the value for sci_patent.pat_Agency
     *
     * @mbg.generated
     */
    public void setPatAgency(String patAgency) {
        this.patAgency = patAgency == null ? null : patAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_PrePublishAudit
     *
     * @return the value of sci_patent.pat_PrePublishAudit
     *
     * @mbg.generated
     */
    public String getPatPrepublishaudit() {
        return patPrepublishaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_PrePublishAudit
     *
     * @param patPrepublishaudit the value for sci_patent.pat_PrePublishAudit
     *
     * @mbg.generated
     */
    public void setPatPrepublishaudit(String patPrepublishaudit) {
        this.patPrepublishaudit = patPrepublishaudit == null ? null : patPrepublishaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_ApplyNum
     *
     * @return the value of sci_patent.pat_ApplyNum
     *
     * @mbg.generated
     */
    public String getPatApplynum() {
        return patApplynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_ApplyNum
     *
     * @param patApplynum the value for sci_patent.pat_ApplyNum
     *
     * @mbg.generated
     */
    public void setPatApplynum(String patApplynum) {
        this.patApplynum = patApplynum == null ? null : patApplynum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_ApplyTime
     *
     * @return the value of sci_patent.pat_ApplyTime
     *
     * @mbg.generated
     */
    public String getPatApplytime() {
        return patApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_ApplyTime
     *
     * @param patApplytime the value for sci_patent.pat_ApplyTime
     *
     * @mbg.generated
     */
    public void setPatApplytime(String patApplytime) {
        this.patApplytime = patApplytime == null ? null : patApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_PublishNum
     *
     * @return the value of sci_patent.pat_PublishNum
     *
     * @mbg.generated
     */
    public String getPatPublishnum() {
        return patPublishnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_PublishNum
     *
     * @param patPublishnum the value for sci_patent.pat_PublishNum
     *
     * @mbg.generated
     */
    public void setPatPublishnum(String patPublishnum) {
        this.patPublishnum = patPublishnum == null ? null : patPublishnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_PublishTime
     *
     * @return the value of sci_patent.pat_PublishTime
     *
     * @mbg.generated
     */
    public String getPatPublishtime() {
        return patPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_PublishTime
     *
     * @param patPublishtime the value for sci_patent.pat_PublishTime
     *
     * @mbg.generated
     */
    public void setPatPublishtime(String patPublishtime) {
        this.patPublishtime = patPublishtime == null ? null : patPublishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_AuthorzationTime
     *
     * @return the value of sci_patent.pat_AuthorzationTime
     *
     * @mbg.generated
     */
    public String getPatAuthorzationtime() {
        return patAuthorzationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_AuthorzationTime
     *
     * @param patAuthorzationtime the value for sci_patent.pat_AuthorzationTime
     *
     * @mbg.generated
     */
    public void setPatAuthorzationtime(String patAuthorzationtime) {
        this.patAuthorzationtime = patAuthorzationtime == null ? null : patAuthorzationtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Remission
     *
     * @return the value of sci_patent.pat_Remission
     *
     * @mbg.generated
     */
    public String getPatRemission() {
        return patRemission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Remission
     *
     * @param patRemission the value for sci_patent.pat_Remission
     *
     * @mbg.generated
     */
    public void setPatRemission(String patRemission) {
        this.patRemission = patRemission == null ? null : patRemission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Cost
     *
     * @return the value of sci_patent.pat_Cost
     *
     * @mbg.generated
     */
    public String getPatCost() {
        return patCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Cost
     *
     * @param patCost the value for sci_patent.pat_Cost
     *
     * @mbg.generated
     */
    public void setPatCost(String patCost) {
        this.patCost = patCost == null ? null : patCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_InvoicePer
     *
     * @return the value of sci_patent.pat_InvoicePer
     *
     * @mbg.generated
     */
    public String getPatInvoiceper() {
        return patInvoiceper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_InvoicePer
     *
     * @param patInvoiceper the value for sci_patent.pat_InvoicePer
     *
     * @mbg.generated
     */
    public void setPatInvoiceper(String patInvoiceper) {
        this.patInvoiceper = patInvoiceper == null ? null : patInvoiceper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Remark
     *
     * @return the value of sci_patent.pat_Remark
     *
     * @mbg.generated
     */
    public String getPatRemark() {
        return patRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Remark
     *
     * @param patRemark the value for sci_patent.pat_Remark
     *
     * @mbg.generated
     */
    public void setPatRemark(String patRemark) {
        this.patRemark = patRemark == null ? null : patRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Penner
     *
     * @return the value of sci_patent.pat_Penner
     *
     * @mbg.generated
     */
    public String getPatPenner() {
        return patPenner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Penner
     *
     * @param patPenner the value for sci_patent.pat_Penner
     *
     * @mbg.generated
     */
    public void setPatPenner(String patPenner) {
        this.patPenner = patPenner == null ? null : patPenner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_patent.pat_Agent
     *
     * @return the value of sci_patent.pat_Agent
     *
     * @mbg.generated
     */
    public String getPatAgent() {
        return patAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_patent.pat_Agent
     *
     * @param patAgent the value for sci_patent.pat_Agent
     *
     * @mbg.generated
     */
    public void setPatAgent(String patAgent) {
        this.patAgent = patAgent == null ? null : patAgent.trim();
    }
}