package com.qaii.domain;

public class Softwarecopyright {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Dept
     *
     * @mbg.generated
     */
    private String softDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Code
     *
     * @mbg.generated
     */
    private String softCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Name
     *
     * @mbg.generated
     */
    private String softName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Writer
     *
     * @mbg.generated
     */
    private String softWriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Author
     *
     * @mbg.generated
     */
    private String softAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Agency
     *
     * @mbg.generated
     */
    private String softAgency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_DevelopEndTime
     *
     * @mbg.generated
     */
    private String softDevelopendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_FirstPublishTime
     *
     * @mbg.generated
     */
    private String softFirstpublishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Num
     *
     * @mbg.generated
     */
    private String softNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_CertificateTime
     *
     * @mbg.generated
     */
    private String softCertificatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Cost
     *
     * @mbg.generated
     */
    private String softCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_InvoicePer
     *
     * @mbg.generated
     */
    private String softInvoiceper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_UpdateTime
     *
     * @mbg.generated
     */
    private String softUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_softwarecopyright.soft_Remark
     *
     * @mbg.generated
     */
    private String softRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.id
     *
     * @return the value of sci_softwarecopyright.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.id
     *
     * @param id the value for sci_softwarecopyright.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Dept
     *
     * @return the value of sci_softwarecopyright.soft_Dept
     *
     * @mbg.generated
     */
    public String getSoftDept() {
        return softDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Dept
     *
     * @param softDept the value for sci_softwarecopyright.soft_Dept
     *
     * @mbg.generated
     */
    public void setSoftDept(String softDept) {
        this.softDept = softDept == null ? null : softDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Code
     *
     * @return the value of sci_softwarecopyright.soft_Code
     *
     * @mbg.generated
     */
    public String getSoftCode() {
        return softCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Code
     *
     * @param softCode the value for sci_softwarecopyright.soft_Code
     *
     * @mbg.generated
     */
    public void setSoftCode(String softCode) {
        this.softCode = softCode == null ? null : softCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Name
     *
     * @return the value of sci_softwarecopyright.soft_Name
     *
     * @mbg.generated
     */
    public String getSoftName() {
        return softName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Name
     *
     * @param softName the value for sci_softwarecopyright.soft_Name
     *
     * @mbg.generated
     */
    public void setSoftName(String softName) {
        this.softName = softName == null ? null : softName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Writer
     *
     * @return the value of sci_softwarecopyright.soft_Writer
     *
     * @mbg.generated
     */
    public String getSoftWriter() {
        return softWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Writer
     *
     * @param softWriter the value for sci_softwarecopyright.soft_Writer
     *
     * @mbg.generated
     */
    public void setSoftWriter(String softWriter) {
        this.softWriter = softWriter == null ? null : softWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Author
     *
     * @return the value of sci_softwarecopyright.soft_Author
     *
     * @mbg.generated
     */
    public String getSoftAuthor() {
        return softAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Author
     *
     * @param softAuthor the value for sci_softwarecopyright.soft_Author
     *
     * @mbg.generated
     */
    public void setSoftAuthor(String softAuthor) {
        this.softAuthor = softAuthor == null ? null : softAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Agency
     *
     * @return the value of sci_softwarecopyright.soft_Agency
     *
     * @mbg.generated
     */
    public String getSoftAgency() {
        return softAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Agency
     *
     * @param softAgency the value for sci_softwarecopyright.soft_Agency
     *
     * @mbg.generated
     */
    public void setSoftAgency(String softAgency) {
        this.softAgency = softAgency == null ? null : softAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_DevelopEndTime
     *
     * @return the value of sci_softwarecopyright.soft_DevelopEndTime
     *
     * @mbg.generated
     */
    public String getSoftDevelopendtime() {
        return softDevelopendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_DevelopEndTime
     *
     * @param softDevelopendtime the value for sci_softwarecopyright.soft_DevelopEndTime
     *
     * @mbg.generated
     */
    public void setSoftDevelopendtime(String softDevelopendtime) {
        this.softDevelopendtime = softDevelopendtime == null ? null : softDevelopendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_FirstPublishTime
     *
     * @return the value of sci_softwarecopyright.soft_FirstPublishTime
     *
     * @mbg.generated
     */
    public String getSoftFirstpublishtime() {
        return softFirstpublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_FirstPublishTime
     *
     * @param softFirstpublishtime the value for sci_softwarecopyright.soft_FirstPublishTime
     *
     * @mbg.generated
     */
    public void setSoftFirstpublishtime(String softFirstpublishtime) {
        this.softFirstpublishtime = softFirstpublishtime == null ? null : softFirstpublishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Num
     *
     * @return the value of sci_softwarecopyright.soft_Num
     *
     * @mbg.generated
     */
    public String getSoftNum() {
        return softNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Num
     *
     * @param softNum the value for sci_softwarecopyright.soft_Num
     *
     * @mbg.generated
     */
    public void setSoftNum(String softNum) {
        this.softNum = softNum == null ? null : softNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_CertificateTime
     *
     * @return the value of sci_softwarecopyright.soft_CertificateTime
     *
     * @mbg.generated
     */
    public String getSoftCertificatetime() {
        return softCertificatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_CertificateTime
     *
     * @param softCertificatetime the value for sci_softwarecopyright.soft_CertificateTime
     *
     * @mbg.generated
     */
    public void setSoftCertificatetime(String softCertificatetime) {
        this.softCertificatetime = softCertificatetime == null ? null : softCertificatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Cost
     *
     * @return the value of sci_softwarecopyright.soft_Cost
     *
     * @mbg.generated
     */
    public String getSoftCost() {
        return softCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Cost
     *
     * @param softCost the value for sci_softwarecopyright.soft_Cost
     *
     * @mbg.generated
     */
    public void setSoftCost(String softCost) {
        this.softCost = softCost == null ? null : softCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_InvoicePer
     *
     * @return the value of sci_softwarecopyright.soft_InvoicePer
     *
     * @mbg.generated
     */
    public String getSoftInvoiceper() {
        return softInvoiceper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_InvoicePer
     *
     * @param softInvoiceper the value for sci_softwarecopyright.soft_InvoicePer
     *
     * @mbg.generated
     */
    public void setSoftInvoiceper(String softInvoiceper) {
        this.softInvoiceper = softInvoiceper == null ? null : softInvoiceper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_UpdateTime
     *
     * @return the value of sci_softwarecopyright.soft_UpdateTime
     *
     * @mbg.generated
     */
    public String getSoftUpdatetime() {
        return softUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_UpdateTime
     *
     * @param softUpdatetime the value for sci_softwarecopyright.soft_UpdateTime
     *
     * @mbg.generated
     */
    public void setSoftUpdatetime(String softUpdatetime) {
        this.softUpdatetime = softUpdatetime == null ? null : softUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_softwarecopyright.soft_Remark
     *
     * @return the value of sci_softwarecopyright.soft_Remark
     *
     * @mbg.generated
     */
    public String getSoftRemark() {
        return softRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_softwarecopyright.soft_Remark
     *
     * @param softRemark the value for sci_softwarecopyright.soft_Remark
     *
     * @mbg.generated
     */
    public void setSoftRemark(String softRemark) {
        this.softRemark = softRemark == null ? null : softRemark.trim();
    }
}