package com.qaii.domain;

public class Thesis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_Subject
     *
     * @mbg.generated
     */
    private String sisSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_Author
     *
     * @mbg.generated
     */
    private String sisAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_Units
     *
     * @mbg.generated
     */
    private String sisUnits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_PublishLocation
     *
     * @mbg.generated
     */
    private String sisPublishlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_PublishTime
     *
     * @mbg.generated
     */
    private String sisPublishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_Status
     *
     * @mbg.generated
     */
    private String sisStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_thesis.sis_Dept
     *
     * @mbg.generated
     */
    private String sisDept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.id
     *
     * @return the value of sci_thesis.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.id
     *
     * @param id the value for sci_thesis.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_Subject
     *
     * @return the value of sci_thesis.sis_Subject
     *
     * @mbg.generated
     */
    public String getSisSubject() {
        return sisSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_Subject
     *
     * @param sisSubject the value for sci_thesis.sis_Subject
     *
     * @mbg.generated
     */
    public void setSisSubject(String sisSubject) {
        this.sisSubject = sisSubject == null ? null : sisSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_Author
     *
     * @return the value of sci_thesis.sis_Author
     *
     * @mbg.generated
     */
    public String getSisAuthor() {
        return sisAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_Author
     *
     * @param sisAuthor the value for sci_thesis.sis_Author
     *
     * @mbg.generated
     */
    public void setSisAuthor(String sisAuthor) {
        this.sisAuthor = sisAuthor == null ? null : sisAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_Units
     *
     * @return the value of sci_thesis.sis_Units
     *
     * @mbg.generated
     */
    public String getSisUnits() {
        return sisUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_Units
     *
     * @param sisUnits the value for sci_thesis.sis_Units
     *
     * @mbg.generated
     */
    public void setSisUnits(String sisUnits) {
        this.sisUnits = sisUnits == null ? null : sisUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_PublishLocation
     *
     * @return the value of sci_thesis.sis_PublishLocation
     *
     * @mbg.generated
     */
    public String getSisPublishlocation() {
        return sisPublishlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_PublishLocation
     *
     * @param sisPublishlocation the value for sci_thesis.sis_PublishLocation
     *
     * @mbg.generated
     */
    public void setSisPublishlocation(String sisPublishlocation) {
        this.sisPublishlocation = sisPublishlocation == null ? null : sisPublishlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_PublishTime
     *
     * @return the value of sci_thesis.sis_PublishTime
     *
     * @mbg.generated
     */
    public String getSisPublishtime() {
        return sisPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_PublishTime
     *
     * @param sisPublishtime the value for sci_thesis.sis_PublishTime
     *
     * @mbg.generated
     */
    public void setSisPublishtime(String sisPublishtime) {
        this.sisPublishtime = sisPublishtime == null ? null : sisPublishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_Status
     *
     * @return the value of sci_thesis.sis_Status
     *
     * @mbg.generated
     */
    public String getSisStatus() {
        return sisStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_Status
     *
     * @param sisStatus the value for sci_thesis.sis_Status
     *
     * @mbg.generated
     */
    public void setSisStatus(String sisStatus) {
        this.sisStatus = sisStatus == null ? null : sisStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_thesis.sis_Dept
     *
     * @return the value of sci_thesis.sis_Dept
     *
     * @mbg.generated
     */
    public String getSisDept() {
        return sisDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_thesis.sis_Dept
     *
     * @param sisDept the value for sci_thesis.sis_Dept
     *
     * @mbg.generated
     */
    public void setSisDept(String sisDept) {
        this.sisDept = sisDept == null ? null : sisDept.trim();
    }
}