package com.qaii.domain;

public class Trademark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Dept
     *
     * @mbg.generated
     */
    private String tradmDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Code
     *
     * @mbg.generated
     */
    private String tradmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_PngAndExplain
     *
     * @mbg.generated
     */
    private String tradmPngandexplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_ApplyPer
     *
     * @mbg.generated
     */
    private String tradmApplyper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Agency
     *
     * @mbg.generated
     */
    private String tradmAgency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Type
     *
     * @mbg.generated
     */
    private String tradmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Item
     *
     * @mbg.generated
     */
    private String tradmItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_ApplyNum
     *
     * @mbg.generated
     */
    private String tradmApplynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_ApplyTime
     *
     * @mbg.generated
     */
    private String tradmApplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_RegisterTime
     *
     * @mbg.generated
     */
    private String tradmRegistertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_ValidTime
     *
     * @mbg.generated
     */
    private String tradmValidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_Cost
     *
     * @mbg.generated
     */
    private String tradmCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_InvoicePer
     *
     * @mbg.generated
     */
    private String tradmInvoiceper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_StatusFollow
     *
     * @mbg.generated
     */
    private String tradmStatusfollow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_trademark.tradm_UpdateTime
     *
     * @mbg.generated
     */
    private String tradmUpdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.id
     *
     * @return the value of sci_trademark.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.id
     *
     * @param id the value for sci_trademark.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Dept
     *
     * @return the value of sci_trademark.tradm_Dept
     *
     * @mbg.generated
     */
    public String getTradmDept() {
        return tradmDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Dept
     *
     * @param tradmDept the value for sci_trademark.tradm_Dept
     *
     * @mbg.generated
     */
    public void setTradmDept(String tradmDept) {
        this.tradmDept = tradmDept == null ? null : tradmDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Code
     *
     * @return the value of sci_trademark.tradm_Code
     *
     * @mbg.generated
     */
    public String getTradmCode() {
        return tradmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Code
     *
     * @param tradmCode the value for sci_trademark.tradm_Code
     *
     * @mbg.generated
     */
    public void setTradmCode(String tradmCode) {
        this.tradmCode = tradmCode == null ? null : tradmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_PngAndExplain
     *
     * @return the value of sci_trademark.tradm_PngAndExplain
     *
     * @mbg.generated
     */
    public String getTradmPngandexplain() {
        return tradmPngandexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_PngAndExplain
     *
     * @param tradmPngandexplain the value for sci_trademark.tradm_PngAndExplain
     *
     * @mbg.generated
     */
    public void setTradmPngandexplain(String tradmPngandexplain) {
        this.tradmPngandexplain = tradmPngandexplain == null ? null : tradmPngandexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_ApplyPer
     *
     * @return the value of sci_trademark.tradm_ApplyPer
     *
     * @mbg.generated
     */
    public String getTradmApplyper() {
        return tradmApplyper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_ApplyPer
     *
     * @param tradmApplyper the value for sci_trademark.tradm_ApplyPer
     *
     * @mbg.generated
     */
    public void setTradmApplyper(String tradmApplyper) {
        this.tradmApplyper = tradmApplyper == null ? null : tradmApplyper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Agency
     *
     * @return the value of sci_trademark.tradm_Agency
     *
     * @mbg.generated
     */
    public String getTradmAgency() {
        return tradmAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Agency
     *
     * @param tradmAgency the value for sci_trademark.tradm_Agency
     *
     * @mbg.generated
     */
    public void setTradmAgency(String tradmAgency) {
        this.tradmAgency = tradmAgency == null ? null : tradmAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Type
     *
     * @return the value of sci_trademark.tradm_Type
     *
     * @mbg.generated
     */
    public String getTradmType() {
        return tradmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Type
     *
     * @param tradmType the value for sci_trademark.tradm_Type
     *
     * @mbg.generated
     */
    public void setTradmType(String tradmType) {
        this.tradmType = tradmType == null ? null : tradmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Item
     *
     * @return the value of sci_trademark.tradm_Item
     *
     * @mbg.generated
     */
    public String getTradmItem() {
        return tradmItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Item
     *
     * @param tradmItem the value for sci_trademark.tradm_Item
     *
     * @mbg.generated
     */
    public void setTradmItem(String tradmItem) {
        this.tradmItem = tradmItem == null ? null : tradmItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_ApplyNum
     *
     * @return the value of sci_trademark.tradm_ApplyNum
     *
     * @mbg.generated
     */
    public String getTradmApplynum() {
        return tradmApplynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_ApplyNum
     *
     * @param tradmApplynum the value for sci_trademark.tradm_ApplyNum
     *
     * @mbg.generated
     */
    public void setTradmApplynum(String tradmApplynum) {
        this.tradmApplynum = tradmApplynum == null ? null : tradmApplynum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_ApplyTime
     *
     * @return the value of sci_trademark.tradm_ApplyTime
     *
     * @mbg.generated
     */
    public String getTradmApplytime() {
        return tradmApplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_ApplyTime
     *
     * @param tradmApplytime the value for sci_trademark.tradm_ApplyTime
     *
     * @mbg.generated
     */
    public void setTradmApplytime(String tradmApplytime) {
        this.tradmApplytime = tradmApplytime == null ? null : tradmApplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_RegisterTime
     *
     * @return the value of sci_trademark.tradm_RegisterTime
     *
     * @mbg.generated
     */
    public String getTradmRegistertime() {
        return tradmRegistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_RegisterTime
     *
     * @param tradmRegistertime the value for sci_trademark.tradm_RegisterTime
     *
     * @mbg.generated
     */
    public void setTradmRegistertime(String tradmRegistertime) {
        this.tradmRegistertime = tradmRegistertime == null ? null : tradmRegistertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_ValidTime
     *
     * @return the value of sci_trademark.tradm_ValidTime
     *
     * @mbg.generated
     */
    public String getTradmValidtime() {
        return tradmValidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_ValidTime
     *
     * @param tradmValidtime the value for sci_trademark.tradm_ValidTime
     *
     * @mbg.generated
     */
    public void setTradmValidtime(String tradmValidtime) {
        this.tradmValidtime = tradmValidtime == null ? null : tradmValidtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_Cost
     *
     * @return the value of sci_trademark.tradm_Cost
     *
     * @mbg.generated
     */
    public String getTradmCost() {
        return tradmCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_Cost
     *
     * @param tradmCost the value for sci_trademark.tradm_Cost
     *
     * @mbg.generated
     */
    public void setTradmCost(String tradmCost) {
        this.tradmCost = tradmCost == null ? null : tradmCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_InvoicePer
     *
     * @return the value of sci_trademark.tradm_InvoicePer
     *
     * @mbg.generated
     */
    public String getTradmInvoiceper() {
        return tradmInvoiceper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_InvoicePer
     *
     * @param tradmInvoiceper the value for sci_trademark.tradm_InvoicePer
     *
     * @mbg.generated
     */
    public void setTradmInvoiceper(String tradmInvoiceper) {
        this.tradmInvoiceper = tradmInvoiceper == null ? null : tradmInvoiceper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_StatusFollow
     *
     * @return the value of sci_trademark.tradm_StatusFollow
     *
     * @mbg.generated
     */
    public String getTradmStatusfollow() {
        return tradmStatusfollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_StatusFollow
     *
     * @param tradmStatusfollow the value for sci_trademark.tradm_StatusFollow
     *
     * @mbg.generated
     */
    public void setTradmStatusfollow(String tradmStatusfollow) {
        this.tradmStatusfollow = tradmStatusfollow == null ? null : tradmStatusfollow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_trademark.tradm_UpdateTime
     *
     * @return the value of sci_trademark.tradm_UpdateTime
     *
     * @mbg.generated
     */
    public String getTradmUpdatetime() {
        return tradmUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_trademark.tradm_UpdateTime
     *
     * @param tradmUpdatetime the value for sci_trademark.tradm_UpdateTime
     *
     * @mbg.generated
     */
    public void setTradmUpdatetime(String tradmUpdatetime) {
        this.tradmUpdatetime = tradmUpdatetime == null ? null : tradmUpdatetime.trim();
    }
}