package com.qaii.domain;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_Type
     *
     * @mbg.generated
     */
    private String workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_Topic
     *
     * @mbg.generated
     */
    private String workTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_Author
     *
     * @mbg.generated
     */
    private String workAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_PublishHouse
     *
     * @mbg.generated
     */
    private String workPublishhouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_PublishTime
     *
     * @mbg.generated
     */
    private String workPublishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sci_work.work_Dept
     *
     * @mbg.generated
     */
    private String workDept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.id
     *
     * @return the value of sci_work.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.id
     *
     * @param id the value for sci_work.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_Type
     *
     * @return the value of sci_work.work_Type
     *
     * @mbg.generated
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_Type
     *
     * @param workType the value for sci_work.work_Type
     *
     * @mbg.generated
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_Topic
     *
     * @return the value of sci_work.work_Topic
     *
     * @mbg.generated
     */
    public String getWorkTopic() {
        return workTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_Topic
     *
     * @param workTopic the value for sci_work.work_Topic
     *
     * @mbg.generated
     */
    public void setWorkTopic(String workTopic) {
        this.workTopic = workTopic == null ? null : workTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_Author
     *
     * @return the value of sci_work.work_Author
     *
     * @mbg.generated
     */
    public String getWorkAuthor() {
        return workAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_Author
     *
     * @param workAuthor the value for sci_work.work_Author
     *
     * @mbg.generated
     */
    public void setWorkAuthor(String workAuthor) {
        this.workAuthor = workAuthor == null ? null : workAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_PublishHouse
     *
     * @return the value of sci_work.work_PublishHouse
     *
     * @mbg.generated
     */
    public String getWorkPublishhouse() {
        return workPublishhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_PublishHouse
     *
     * @param workPublishhouse the value for sci_work.work_PublishHouse
     *
     * @mbg.generated
     */
    public void setWorkPublishhouse(String workPublishhouse) {
        this.workPublishhouse = workPublishhouse == null ? null : workPublishhouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_PublishTime
     *
     * @return the value of sci_work.work_PublishTime
     *
     * @mbg.generated
     */
    public String getWorkPublishtime() {
        return workPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_PublishTime
     *
     * @param workPublishtime the value for sci_work.work_PublishTime
     *
     * @mbg.generated
     */
    public void setWorkPublishtime(String workPublishtime) {
        this.workPublishtime = workPublishtime == null ? null : workPublishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sci_work.work_Dept
     *
     * @return the value of sci_work.work_Dept
     *
     * @mbg.generated
     */
    public String getWorkDept() {
        return workDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sci_work.work_Dept
     *
     * @param workDept the value for sci_work.work_Dept
     *
     * @mbg.generated
     */
    public void setWorkDept(String workDept) {
        this.workDept = workDept == null ? null : workDept.trim();
    }
}