package com.qaii.dao;

import com.qaii.domain.Govfund;

public interface GovfundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    int insert(Govfund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    int insertSelective(Govfund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    Govfund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Govfund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govfund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Govfund record);
}