package com.qaii.dao;

import com.qaii.domain.Govplatform;

public interface GovplatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    int insert(Govplatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    int insertSelective(Govplatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    Govplatform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Govplatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govplatform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Govplatform record);
}