package com.qaii.dao;

import com.qaii.domain.Govreward;

public interface GovrewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    int insert(Govreward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    int insertSelective(Govreward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    Govreward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Govreward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govreward
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Govreward record);
}