package com.qaii.dao;

import com.qaii.domain.Govsubject;

public interface GovsubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    int insert(Govsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    int insertSelective(Govsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    Govsubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Govsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_govsubject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Govsubject record);
}