package com.qaii.dao;

import com.qaii.domain.Patent;

public interface PatentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    int insert(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    int insertSelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    Patent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_patent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Patent record);
}