package com.qaii.dao;

import com.qaii.domain.Softwarecopyright;

public interface SoftwarecopyrightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    int insert(Softwarecopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    int insertSelective(Softwarecopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    Softwarecopyright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Softwarecopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_softwarecopyright
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Softwarecopyright record);
}