package com.qaii.dao;

import com.qaii.domain.Thesis;

public interface ThesisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    int insert(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    int insertSelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    Thesis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_thesis
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Thesis record);
}