package com.qaii.dao;

import com.qaii.domain.Trademark;

public interface TrademarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    int insert(Trademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    int insertSelective(Trademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    Trademark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Trademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sci_trademark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Trademark record);
}